### ISSUE TITLE
[32-bit] libexample

### ISSUE THREAD

**Issue by jwinarske** [jerel/membrane#20]
Looks like the example library build is not 32-bit ready:
https://github.com/meta-flutter/meta-flutter/actions/runs/3034466594

**Comment by jerel** [comment]
From the docs it seems like Flutter is dropping (or never thoroughly had?) 32-bit support: https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms#unsupported-platforms In their **Unsupported Platforms** section they call out `Linux | Any 32-bit platform` as well as Windows 32-bit, etc. With that in mind do you plan to keep 32-bit support in meta-flutter going forward?

Supporting 32-bit platforms in Membrane seems somewhat problematic at first glance as the asynchronous FFI port between the two languages is exposed by Dart as a 64-bit integer.

**Comment by jwinarske** [comment]
That just means they aren't actively testing 32-bit builds.  They recently merged 32-bit build break fix for 3.3.0.  Until Dart deprecates it, it's still fair game.

The flutter_rust_bridge example does cross-compile and run with 32-bit.  So that's fine.  There's a workable solution for the 32-bit variety.

**Comment by jerel** [comment]
Looks like it's been long enough that the build logs got deleted from the above job _but_ if I'm remembering the error message correctly then this issue is also closed by #43. We were using `c_long` which on some systems is only represented by 32 bits instead of it being 64 bits like on most Linux environments.

If there's still an issue that appears on 32 bit systems we can reopen.

**Comment by jwinarske** [comment]
Yeah I haven't tested 32-bit for a hot minute.  I'll check in the next month
